src/DynamicPolynomials.jl
See [this PR](https://github.com/blegat/MultivariatePolynomials.jl/pull/47) in MultivariatePolynomials.
It felt a little bit silly to create an extra file just for one function, but it couldn't be in `var.jl` and the rest didn't fit really...
=> Add similarvariable

src/cmult.jl
I missed one line in the last PR :(
=> Fix findfirst bug

REQUIRE, src/diff.jl, src/poly.jl, test/mvp.jl
Fixes the inference issue mentioned by @saschatimme in https://github.com/JuliaAlgebra/DynamicPolynomials.jl/pull/15#issuecomment-394385898
=> Julia v0.7 fixes

src/mono.jl, test/mono.jl
Fixes https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/issues/81
=> Add conversion from Int to Monomial

src/DynamicPolynomials.jl
=> Export differentiate, subs, variables from MP

src/DynamicPolynomials.jl
These are also handy to have available by default.
=> Reexport mindegree and maxdegree

src/var.jl, test/mono.jl
Accidentally merged #32 into 0.7-only instead of master. Now rebased onto master and this new PR.
=> Improve @polyvar (2)

REQUIRE, src/DynamicPolynomials.jl
Let's reexport all exports from MultivariatePolynomials, since everybody already imports both packages all the time...
=> Reexport MultivariatePolynomials

REQUIRE, src/var.jl
See https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/pull/92
=> Change printing of variables with indices

src/subs.jl, test/poly.jl
Closes https://github.com/JuliaAlgebra/DynamicPolynomials.jl/issues/30
=> Throw if not all variables are set

src/subs.jl, test/runtests.jl
Closes https://github.com/JuliaAlgebra/DynamicPolynomials.jl/issues/47
=> Fix subs with no variables

Project.toml, src/DynamicPolynomials.jl, test/mono.jl
=> Implement variable_union_type

.travis.yml
DifferentialEquations.jl problems on v1.3 seem to stem from here, so this bump should detect this in the tests.
https://travis-ci.org/JuliaDiffEq/DifferentialEquations.jl/jobs/618925886#L439
=> Test on v1.3

.travis.yml, Project.toml, src/DynamicPolynomials.jl, src/cmult.jl, src/comp.jl, src/mono.jl, src/monovec.jl, src/mult.jl, src/operators.jl, src/poly.jl, src/subs.jl, src/term.jl, test/comp.jl, test/mutable_arithmetics.jl, test/runtests.jl
cc @tweisser @Peiffap @saschatimme
=> Implement MutableArithmetics

src/ncmult.jl
Closes https://github.com/JuliaAlgebra/DynamicPolynomials.jl/issues/58
=> Fix multiplication with empty monomial

src/operators.jl
Improve performance for https://github.com/JuliaAlgebra/DynamicPolynomials.jl/issues/64
=> Only call _add_variables if needed

src/mult.jl, src/term.jl
See https://github.com/JuliaAlgebra/DynamicPolynomials.jl/issues/69
=> Define term(coef, mono)

src/subs.jl, test/runtests.jl
Closes https://github.com/JuliaAlgebra/DynamicPolynomials.jl/issues/70
=> Fix substitution with noncommutative variables

src/cmult.jl, src/mult.jl, src/ncmult.jl
The closure approach seems to trigger some inference issue so this should be faster.
=> Faster monomial multiplication

Project.toml, src/DynamicPolynomials.jl, src/promote.jl
See https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/issues/165
=> Fix promotion with nonconcrete types

src/subs.jl, src/var.jl, test/runtests.jl
Closes https://github.com/JuliaAlgebra/DynamicPolynomials.jl/issues/92
Closes https://github.com/JuliaAlgebra/DynamicPolynomials.jl/issues/96
cc @votroto
=> Drop variables not in any substitution

src/cmult.jl, test/mono.jl
Closes https://github.com/JuliaAlgebra/DynamicPolynomials.jl/issues/104
=> Fix mapexponents! with different variables

.github/workflows/ci.yml, src/DynamicPolynomials.jl, src/cmult.jl, src/comp.jl, src/diff.jl, src/monovec.jl, src/ncmult.jl, src/operators.jl, src/poly.jl, src/subs.jl, test/mono.jl, test/mutable_arithmetics.jl, test/poly.jl
See https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/pull/199
=> Update with MultivariatePolynomials#bl/term

.github/workflows/ci.yml, src/cmult.jl, src/mult.jl, src/operators.jl, src/poly.jl
Needed for https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/pull/235
=> Changes need for mutable pseudo_rem

src/operators.jl, test/runtests.jl
Closes https://github.com/JuliaAlgebra/DynamicPolynomials.jl/issues/141
=> Fix mutation of power of monomial

src/div.jl, test/mono.jl
It's better than an incorrect implementation
=> Error for divides with noncommutative

src/operators.jl
I don't remember what this was but it is not used anymore
=> Remove myminivect
