JuliaAlgebra/DynamicPolynomials.jl

REQUIRE
src/DynamicPolynomials.jl
src/cmult.jl
src/diff.jl
src/ncmult.jl
src/subs.jl

Previously findfirst and findlast returned 0 if for no entry the
predicate returned `true`. Now it returns `nothing`. The changes should be backwards compatible to 0.6.
Locally the tests segfault, maybe it works on travis 🤷‍♂️

Handle findfirst / findlast change

---

.travis.yml

The MacOS cluster from travis seems to be quite unreliable / needs a looooot of time. Since there is no system specific stuff here I think it is fine to only run linux.

Disable OSX on travis-ci

---

src/mult.jl

If the coefficient type is a custom type, it might not define `*(::T, ::Vector{T})`

Use dot syntax

---

src/diff.jl
src/mult.jl
src/poly.jl
src/subs.jl

A little bit less deprecation warnings.

uninitialized -> undef

---

src/DynamicPolynomials.jl

Directly dispatch on the `similarvariable(f, symb)` constructor.
Previously the symbol was wrapped in a `Val` and thus forced compilation
for each new symbol.
Before
```julia
@time MP.similarvariable(f, gensym(:x0))
0.004129 seconds (289 allocations: 16.340 KiB)
##x0#687
```
Now
```julia
@time MP.similarvariable(f, gensym(:x0))
0.000017 seconds (14 allocations: 608 bytes)
##x0#688
```

Avoid unnecessary compilation for similarvariable

---

src/var.jl
test/mono.jl

Here is a little thing I missed from time to time. This adds the possibility to construct matrices of variables via
```julia
@polyvar x[1:3, 1:2]
```
What do you think?

Add possibility to construct matrix with @[nc]polyvar

---

src/subs.jl
test/mono.jl
test/poly.jl

If I have to evaluate DynamicPolynomials in 99% of my cases I end up doing
```julia
f(MP.variables(f)=>x)
```
This PR adds more callable cases to support
```julia
f(1, 2) # fallback  to  f(MP.variables(f)=>(1, 2))
f((1, 2))  # fallback  to  f(MP.variables(f)=>(1, 2))
f([1, 2])  # fallback  to  f(MP.variables(f)=>[1, 2])
```
I don't think that this leads to substantially more confusion than the current requirement to always explicitly provide the variables.

Add default evaluations routines which assume default variable ordering

---

src/mono.jl
test/mono.jl

This reverts #14 for Julia 0.6 to adress #18. This is not really satisfactory, but I would appreciate if we could get this merged for the time until we all reach the 0.7 happy land.

Revert #14 for Julia 0.6

---

src/operators.jl

It was failing with JuMP master since the affine expression constructor with only one argument assumes that it's the constant of the affine expression.
I need to release this for tomorrow

Use convert explicitely

---

src/var.jl
test/mono.jl

This changes the behaviour of `@polyvar` to always return a tuple of the declared variables. The previous behaviour seems to lead to some confusion.
```julia
#previously
julia> @polyvar a b c
c
#now
julia> @polyvar a b c
(a, b, c)
```
This addresses [#]85(https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/issues/85) in MultivariatePolynomials. cc @chriscoey
Note that this PR is currently against the 0.7 branch, I could backport this to 0.6 if there is some need to get this in a 0.6 release.

Improve @polyvar

---

.travis.yml
src/monovec.jl
src/poly.jl

It seems that 0.7 had no deprecation warning for `Base.endof`. With this change everything works on Julia 1.0 🎉

Fix errors on 1.0

---

src/monovec.jl
src/var.jl

Addresses #43.
However `emptymonovec` isn't implemented in TypedPolynomials yet.

remove emptymonovec method for tuples of polyvars

---

Project.toml
src/cmult.jl
src/mult.jl
src/operators.jl

Doing `MA.operate!(op(p, q), ...)` could modify `p` or `q` as some vectors were not copied. This PR fixes this.

Copy internal vectors instead of giving the same instance

---

src/mono.jl
src/poly.jl
test/mutable_arithmetics.jl

When generating a polynomial `q = zero(p)`, using mutable operations on `p` had an impact on `q`. This is should be fixed now. 
In particular 
```julia
@polyvar x y
p = x^2 + x + 1
q = rem(p, [x^2-y])
```
throws an error without this fix.

Close issue #62

---

src/mult.jl
test/runtests.jl

Fix of [issue #80](https://github.com/JuliaAlgebra/DynamicPolynomials.jl/issues/80)
Overwrite `multconstant` of *MultivariatePolynomials* so that in case of `α==0` the variables of `p` are kept.
Else do the same as before (see `operators.jl` in *MultivariatePolynomials*).

Keep variables for constant zero Polynomials

---

src/mult.jl

This was incorrect, e.g. multiplying polynomials of JuMP.AffExpr was failing because `(MA.promote_operation(MA.add_mul, AffExpr, AffExpr)` is `AffExpr` while it should be `QuadExpr`.

Fix promotion of multiplication

---

src/mult.jl

I didn't check, but unbound type parameters often cause performance issues, so this may not be merely cosmetic.

remove unbound type parameters

---

src/monomial_vector.jl

Currently, it ends up in `OutOfMemoryError`

Error on negative degree for monomials

---

src/var.jl
test/mono.jl

Rather than creating a variable with `Variable(name, V, M)`,
sometimes it's easier to create one with `Variable{V,M}(name)`.
This allows one to create a new variable from an old one with
`typeof(oldvar)(newname)`.

Support VT("name") where VT::Type{<:Variable}

---

src/var.jl

@blegat thanks for the quick fix. 
Looks like `ordering` for polynomials would still not work, this is a quick fix.

A fix for ordering(poly)

---

src/DynamicPolynomials.jl
src/anti_diff.jl
test/mono.jl
test/poly.jl

This patch adds an implementation of the `antidifferentiate` function for both monomials and polynomials (fixing #157).
The function `antidifferentiate(p, x)` works by either returning the product `p*x` if `p` has no term with variable `x`, or by incrementing the powers and adjusting the coefficients to match (thereby always ensuring that the antiderivative evaluates to zero whenever `x` is zero).
I included some basic unit tests as well. I did not run `JuliaFormatter.jl` over the codebase, since numerous other files are not formatted according to those formatting rules...
Let me know if anything is missing. If this lands, I would appreciated a new version to be used in my own project.

Add antidifferentiation

---

src/monomial_vector.jl
test/comp.jl

All orders should hopefully work now. The `Reverse` that are not `Graded` should probably not be allowed but let's wait to see what breaks since this ship has sailed
Closes https://github.com/JuliaAlgebra/DynamicPolynomials.jl/issues/138

Fix monomials for LexOrder

---

src/mono.jl
test/mono.jl

That is clashing with MultivariateBases. This type shouldn't be used anyway, it's better to use MultivariatePolynomials' abstract types
This can go along https://github.com/JuliaAlgebra/DynamicPolynomials.jl/pull/121 in a breaking release

Stop exporting Monomial

---

Project.toml
src/comp.jl
src/mult.jl
src/operators.jl
src/poly.jl

[BREAKING] Remove term iterator behavior of polynomial

---

Project.toml

Not sure why it's there, and no `using Pkg` or `import Pkg` statements seem to exist in the repo.

Remove `Pkg` from dependencies

---

Project.toml
src/operators.jl
test/mutable_arithmetics.jl

Requires https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/pull/339, CI is temporarily set up to use it.

refactor: use new `polynomial_merge!`
